# Generated by Django 4.2.1 on 2023-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "belongs_to"), name="unique_category"
            ),
        ),
    ]
