# Generated by Django 4.2.1 on 2023-05-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_accounttype_type"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="from_action",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense",
                to="accounts.accountaction",
            ),
        ),
    ]
