# Generated by Django 4.2.4 on 2023-08-11 15:24

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="slug",
            field=models.SlugField(
                default=functools.partial(
                    django.utils.crypto.get_random_string, *(15,), **{}
                ),
                max_length=120,
                null=True,
            ),
        ),
    ]
