# Generated by Django 4.2.4 on 2023-08-11 15:25
import functools

from django.db import migrations, models
from django.utils.crypto import get_random_string


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_auto_20230811_2325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="slug",
            field=models.SlugField(
                default=functools.partial(get_random_string, *(15,), **{}),
                max_length=120,
                unique=True,
            ),
        ),
    ]
