# Generated by Django 4.2.1 on 2023-06-11 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_account_unique_together_account_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalance",
            name="belongs_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_balances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
