# Generated by Django 4.2.5 on 2023-09-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_auto_20230811_2325"),
        ("events", "0002_event_unique_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense",
                to="expenses.expense",
            ),
        ),
    ]
