version: "3"

services:
  expense_db:
    container_name: expense_db
    image: postgres:14-alpine
    env_file:
      - ./postgres/.env

  expense_cache:
    container_name: expense_cache
    image: redis:7-alpine

  expense_be: &base_app
    container_name: expense_be
    build:
      context: ../
      dockerfile: ./docker/expense/prod.Dockerfile
    command: /start
    env_file:
      - ./expense/.env.prod
    depends_on:
      - expense_db
      - expense_cache
    ports:
      - 8000:80

  expense_worker:
    <<: *base_app
    image: expense_worker
    container_name: expense_worker
    depends_on:
      - expense_db
      - expense_cache
      - expense_be
    ports: []
    command: python manage.py run_huey
